begin;
grant usage on schema tenopr,terep,terep_dirty,testg to "pepsi_pgsql_ob_ro";
grant select on all tables in schema tenopr,terep,terep_dirty,testg to "pepsi_pgsql_ob_ro";
alter default privileges in schema tenopr,terep,terep_dirty,testg grant select on tables to "pepsi_pgsql_ob_ro";
GRANT ALL privileges ON ALL TABLES IN SCHEMA terep_cstm TO "pepsi_pgsql_ob_ro";
GRANT CREATE ON SCHEMA terep_cstm TO "pepsi_pgsql_ob_ro";
GRANT USAGE ON SCHEMA terep_cstm TO "pepsi_pgsql_ob_ro";
GRANT SELECT ON ALL TABLES IN SCHEMA terep_cstm TO "pepsi_pgsql_ob_ro";
ALTER DEFAULT PRIVILEGES IN SCHEMA terep_cstm grant all on tables to "pepsi_pgsql_ob_ro";
commit;
